services:
  frontend:
    container_name: frontend
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    depends_on:
      - backend
    ports:
      - "3001:3000"
    command: npm start
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
      - node_modules:/app/frontend/node_modules

  backend:
    container_name: backend
    hostname: backend
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    ports:
      - '3000:3000'
    command: rails server -b 0.0.0.0
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    tty: true
    stdin_open: true

  db:
    container_name: postgres
    hostname: postgres
    image: postgres:14
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

volumes:
  db:
  node_modules:
