source "https://rubygems.org"

gem "bcrypt"
gem "bootsnap", require: false
gem "importmap-rails"
gem "kamal", require: false
gem "pg"
gem "propshaft"
gem "puma", ">= 5.0"
gem "rails", "8.0.0"
gem "solid_cable"
gem "solid_cache"
gem "solid_queue"
gem "stimulus-rails"
gem "thruster", require: false
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem 'byebug', '11.1.3'
  gem 'factory_bot_rails', '6.4.4'
  gem 'pry-byebug', '3.10.1'
  gem 'pry-doc', '1.5.0'
  gem 'pry-rails', '0.3.11'
  gem 'pry-stack_explorer', '0.6.1'
  gem 'rspec-rails', '7.1.0'
  gem 'rspec-request_describer', '0.6.0'
end

group :development do
  gem 'rubocop', require: false
  gem 'rubocop-capybara', require: false
  gem 'rubocop-factory_bot', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'rubocop-rspec_rails', require: false
end
